### ISSUE TITLE
Bubble tab stutters 

### ISSUE THREAD

**Issue by dighechinmay** [akshay2211/BubbleTabBar#13]
Hi,

I am trying to load BubbleTabBar in my activity. But because there was slow loading I set offScreenPageLimit to 1 (default). I have checked network calls in my app prior to setting offscreenpagelimit to my viewpager.

Everything loads properly but when I try to switch between the tabs, it stutters. The transition isn't smooth. Noticing a lag.

Can you help?

**Comment by akshay2211** [comment]
Hey @dighechinmay 
can you provide a video or share code so this can be replicated?

**Comment by dighechinmay** [comment]
Hi akshay2211,

In my activity, I am displaying 3 fragments. 

`viewPager.adapter = SectionViewPagerAdapter(supportFragmentManager)
        viewPager.setDurationScroll(1000)
        viewPager.offscreenPageLimit = 1
        viewPager.setPagingEnabled(false)

        bubbleTabBar.addBubbleListener(object : OnBubbleClickListener {
            override fun onBubbleClick(id: Int) {
                when (id) {
                    R.id.home -> viewPager.currentItem = 0
                    R.id.log -> viewPager.currentItem = 1
                    R.id.setting -> viewPager.currentItem = 2
                }
            }
        })
        bubbleTabBar.setupBubbleTabBar(viewPager)`

when I try to change the tabs, there is roughly 1 sec delay. it works okay when offscreenPageLimit is set to 3 but then  the initial loading of the activity is very slow. 
I have removed all the network calls from each of the fragment. still it loads slow.

**Comment by akshay2211** [comment]
you can refer the sample [app](https://github.com/akshay2211/BubbleTabBar/blob/master/app/src/main/java/com/fxn/bubbletabbarapp/MainActivity.kt)
I guess you are doing too much work on your main thread.
try using the library in any new test project, if it works fine, then maybe you are doing something else that is causing the stutter.
