### ISSUE TITLE
No option to add notification badges count icon on bubble tab bar icon

### ISSUE THREAD

**Issue by mala9974025544** [akshay2211/BubbleTabBar#15]

**Comment by akshay2211** [comment]
Hello @mala9974025544,
thanks for trying out [BubbleTabBar](https://github.com/akshay2211/BubbleTabBar).
I will surely add this feature in the next release.

**Comment by DevKenny** [comment]
Hi @akshay2211, is there a way i can add a badge to a bar item? Thank you
