### ISSUE TITLE
ViewPager2 Support

### ISSUE THREAD

**Issue by ionate12** [akshay2211/BubbleTabBar#17]
Hey akshay2211,
I just updated my project from ViewPager to ViewPager2 and found out that your library does not support it. Are there any thoughts of updating your code?
Btw, can you please suggest any work-around solutions to alternate this: 
``` 
fun setupBubbleTabBar(viewPager: ViewPager) {
        viewPager.addOnPageChangeListener(object : ViewPager.OnPageChangeListener {
            override fun onPageScrollStateChanged(state: Int) {
            }

            override fun onPageScrolled(
                position: Int,
                positionOffset: Float,
                positionOffsetPixels: Int
            ) {
            }

            override fun onPageSelected(position: Int) {
                setSelected(position)
            }
        })
    }
```
Thanks. 
Ionate12

**Comment by andre00nogueira** [comment]
@ionate12 I'm currently attacking this issue. Soon the library will be compatible with **ViewPager2**. :metal:
