### ISSUE TITLE
Change Tab Colors

### ISSUE THREAD

**Issue by ghulamsabir** [akshay2211/BubbleTabBar#2]
![bottombar](https://user-images.githubusercontent.com/17097481/64115397-f4657380-cda8-11e9-8405-f3cfe6d1fd7c.PNG)

Like this

**Comment by akshay2211** [comment]
Hello @ghulamsabir,
Thanks for trying out [BubbleTabBar](https://github.com/akshay2211/BubbleTabBar)
can you please share the XML of BubbleTabBar 
you might have given the background color as well as the colors of the tabs both purple.
P.S. if that's not the case kindly share the scenario where I can replicate this.

**Comment by hoanganhtuan95ptit** [comment]
@akshay2211 bubbletab_disabled_icon_color not working

This is my code
```
    <com.fxn.BubbleTabBar
        android:id="@+id/bubbleTabBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:elevation="0dp"
        android:padding="7dp"
        app:bubbletab_disabled_icon_color="#ffffff"
        app:bubbletab_horizontal_padding="20dp"
        app:bubbletab_icon_size="20dp"
        app:bubbletab_menuResource="@menu/menu_edit"
        app:bubbletab_title_size="16sp"
        app:bubbletab_vertical_padding="10dp" />
```

**Comment by hoanganhtuan95ptit** [comment]
@ghulamsabir  @akshay2211 

Replace the code in Bubble.kt
```
       if (isEnabled) {
            icon.setColorStateListAnimator(
                    color = item.iconColor,
                    unselectedColor = Color.parseColor("#1b1b1b")
            )
        }
```

by

``
      if (isEnabled) {
            icon.setColorStateListAnimator(
                    color = item.iconColor,
                    unselectedColor = item.disabled_icon_color
            )
        }`
```
Thank you!!

**Comment by akshay2211** [comment]
Hey @hoanganhtuan95ptit 
Thanks for the help. it is updated in the new version [1.0.3](https://github.com/akshay2211/BubbleTabBar#download)
