### ISSUE TITLE
Background is not set properly for API < 23

### ISSUE THREAD

**Issue by kmikusek** [akshay2211/BubbleTabBar#22]
It is a GradientDrawable.setTint() issue. Solution for `LinearLayout.setCustomBackground(color: Int, alpha: Float)` method:

`DrawableCompat.setTint( DrawableCompat.wrap(drawable), color)`

**Comment by akshay2211** [comment]
@kmikusek Thank you for the suggestion.
changes have been updated in the latest release [1.0.6](https://github.com/akshay2211/BubbleTabBar#download)
