### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by serrokitskiy** [akshay2211/BubbleTabBar#30]
classpath 'com.android.tools.build:gradle:4.2.1'

When delete jcenter() i get

Could not GET 'http://dl.bintray.com/lukaville/maven/com/fxn769/bubbletabbar/1.0.6/bubbletabbar-1.0.6.pom'. Received status code 403 from server: Forbidden

**Comment by akshay2211** [comment]
Hello @serrokitskiy 
you can use BubbleTabbar with the new implementation URL

`implementation  'io.ak1:bubbletabbar:1.0.7'`

which is now hosted on maven central
