### ISSUE TITLE
Is there any way to change the shape of the selected bubble?

### ISSUE THREAD

**Issue by botondsulyok** [akshay2211/BubbleTabBar#35]
I would like to make it more like a square with rounded corners.

**Comment by akshay2211** [comment]
Hello @botondsulyok 
you can now manipulate the tab corner radius by adding 

<io.ak1.BubbleTabBar
                app:bubbletab_tab_corner_radius="10dp"
                ... />

in the XML with the new version of BubbleTabBar
`implementation  'io.ak1:bubbletabbar:1.0.8'`
