### ISSUE TITLE
Change selected item programatically

### ISSUE THREAD

**Issue by Tsabary** [akshay2211/BubbleTabBar#5]
Sometimes there's a need to change the selected item programatically, without the user clicking the item (automatic navigation based on certain actions). Is there a function to do it with this library?

**Comment by akshay2211** [comment]
Hey @Tsabary 
Thanks for using [BubbleTabBar](https://github.com/akshay2211/BubbleTabBar)

you can use
`bubbleTabBar.setSelected(0)`
with the position of selected tab as param

P.S. kindly use the latest version [1.0.3](https://github.com/akshay2211/BubbleTabBar#download)

**Comment by ekripssolutions** [comment]
How can i expand the selected bubbletab indicator programmatically? The above solution isn't working for me. Am using it inside a fragment as a child fragment
