### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by harshsingh98** [akshay2211/BubbleTabBar#7]
For "app:bubbletab_custon_font" attribute, suggestions show @strings which is wrong IMHO, It should show @font instead. Please reply how can one apply custom font.

Regards

**Comment by DawnImpulse** [comment]
any updates for this issue ?

**Comment by akshay2211** [comment]
Hello @harshsingh98 @DawnImpulse 
Thanks for using [BubbleTabBar](https://github.com/akshay2211/BubbleTabBar)
this bug is fixed in the latest [release](https://github.com/akshay2211/BubbleTabBar#download)
