### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by huutho-dev** [akshay2211/BubbleTabBar#8]
Thanks you **akshay2211** for providing me a great library. I love using it!
But, How I can keep my icon color?

**Comment by jaikeerthick** [comment]
> Thanks you **akshay2211** for providing me a great library. I love using it!
> But, How I can keep my icon color?

In your menu.xml file, use `android:iconTint="@color/any_color"` to set color :

`<item
        android:id="@+id/your_id" 
        android:icon="@drawable/ic_icon"
        android:title="title"
        android:checked="true"
        android:iconTint="@color/any_color"/>`
