### ISSUE TITLE
Make tab scrollable

### ISSUE THREAD

**Issue by IvanMazzoli** [akshay2211/BubbleTabBar#9]
First of all, thanks for your library!
I've got a problem with BubbleTabBar: while it looks awesome on my tablet on my phone if I've got too many items the icons are squished/cut and the same happens with the text.
Since I can't remove any item from this bar, do you think it's possible to make it scrollable to fit (theorically) any number of items without cutting them?

![Screenshot_20200217_180341_it tipsyapp caneva](https://user-images.githubusercontent.com/7896815/74673627-de5d3b00-51af-11ea-8131-72068866441b.jpg)

**Comment by RifqiSah** [comment]
You should not use more than five items, according to [Google Material Design](https://material.io/components/bottom-navigation/#usage).

```
Don’t use more than five destinations. For those cases, try tabs or a navigation drawer.
```

Thanks

**Comment by akshay2211** [comment]
Hello @IvanMazzoli  
thanks for using [BubbleTabBar](https://github.com/akshay2211/BubbleTabBar)
its just as @RifqiSah  suggested.
